# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html

fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: 
        include_format: false
    body_listener: true
    
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: false, fallback_format: json, priorities: [ json ] }
            - { path: ^/, prefer_extension: true, fallback_format: html, priorities: [ html ] }
    
    versioning:
        enabled: true
        default_version: v1
        #resolvers:
            #query:
                #enabled: true
               # parameter_name: version

    view:
        view_response_listener:  true

sensio_framework_extra:
    view: { annotations: true }
