# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html

fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: 
        include_format: false
    body_listener: true
    
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json ], fallback_format: json, prefer_extension: false }
            - { path: ^/v1,  priorities: [ json ], fallback_format: json, prefer_extension: false }
            # - { path: ^/, prefer_extension: false, fallback_format: html, priorities: [ html ] }
            #- { path: ^/, prefer_extension: true, fallback_format: html, priorities: [ html ] }
    
    versioning:
        enabled: true
        default_version: v1

    view:
        view_response_listener:  true

    serializer:
        serialize_null: true

#sensio_framework_extra:
  #  view: { annotations: false }
