security:
    encoders:
        App\Security\User:
            algorithm: plaintext

    providers:
        app_user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        userAuthenticationVerify:
            pattern:  ^/v1/api/userauthverify/login
            stateless: true
            anonymous: true

        api:
            pattern:   ^/v1/api
            stateless: true
            anonymous: false
            lexik_jwt: ~ 
            provider: app_user_provider
            guard:
                authenticators:
                    -   api.jwt_token_authenticator

    access_control:
        - { path: ^/v1/api/userauthverify/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/api, roles: ROLE_USER }
