security:
    encoders:
        App\Entity\User:
            algorithm: sha512

    providers:
        app_user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        userAuthenticationVerify:
            pattern:  ^/v1/api/userauthverify/login
            stateless: true
            anonymous: true
            # json_login:
            # #     # username_path: email
            # #     # password_path: password
            #     check_path: /v1/api/userauthverify/login
            #     success_handler: lexik_jwt_authentication.handler.authentication_success
            #     failure_handler: lexik_jwt_authentication.handler.authentication_failure
                
            provider: app_user_provider

        api:
            pattern:   ^/v1/api
            stateless: true
            anonymous: false
            lexik_jwt: ~ 
            guard:
               authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/v1/api/userauthverify/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/api, roles: ROLE_USER }
