security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/v1/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /v1/api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        register:
            pattern:  ^/v1/api/register
            stateless: true
            anonymous: true

        auth_verify:
            pattern:  ^/v1/api/authverify
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
                    
    access_control:
        - { path: ^/v1/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/api/authverify, roles: IS_AUTHENTICATED_FULLY }

    