register:
    path: /v1/api/register
    controller: App\Controller\AuthController::register
    methods: POST

auth_verify:
    path: /v1/api/authverify
    controller: App\Controller\AuthController::authverify

api_login_check:
    path:     /v1/api/login_check
    methods:  [POST]
