register:
    path: /v1/api/register
    controller: App\Controller\AuthController::register
    methods: POST

auth_verify:
    path: /{version}/api/authverify
    controller: App\Controller\AuthController::authverify

api_login_check:
    path:     /v1/api/login_check
    methods:  [POST]

v1test:
    path:  /{version}/api/test
    controller: App\Controller\v1\ShareController::getTestAction
    #condition: "request.attributes.get('version') in ['v1', 'v2']"
    condition:  "request.attributes.get('version') == 'v1'"
    requirements: 
        version: 'v1|v2'

guest_api:
    path:  /{version}/api/guesttest
    controller: App\Controller\TestController::test1
    condition:  "request.attributes.get('version') == 'v1'"
